sonar.projectKey=tinuvi_auth0-oauth-client
sonar.organization=tinuvi

sonar.language=py
sonar.python.version=3.14

sonar.sources=auth0_oauth_client
sonar.tests=tests
sonar.exclusions=samples/**,**/migrations/**
sonar.coverage.exclusions=samples/**,**/migrations/**

sonar.python.coverage.reportPaths=tests-reports/coverage.xml
sonar.python.xunit.reportPath=tests-reports/junit.xml

sonar.verbose=false
