# Generated by Django 5.2.11 on 2026-02-08 22:55

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("user_id", models.CharField(max_length=128, unique=True, verbose_name="User ID")),
                ("refresh_token", models.CharField(max_length=128, verbose_name="Refresh Token")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountLinking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("primary_user_id", models.CharField(max_length=128, verbose_name="Primary User ID")),
                ("secondary_provider", models.CharField(max_length=128, verbose_name="Provider")),
                ("secondary_user_id", models.CharField(max_length=128, verbose_name="Secondary User ID")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("primary_user_id", "secondary_provider", "secondary_user_id"),
                        name="unique_account_linking",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False, verbose_name="Id"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "connected_account_id",
                    models.CharField(max_length=128, unique=True, verbose_name="Connected Account ID"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("provider", models.CharField(max_length=128, verbose_name="Provider")),
                ("user_id_owner", models.CharField(max_length=128, verbose_name="User ID Owner")),
                ("is_account_linked", models.BooleanField(default=False)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user_id_owner", "provider"), name="unique_connected_account")
                ],
            },
        ),
    ]
